### PR TITLE
Added line null terminator for execve

### PR DESCRIPTION
**Pull request by 5unr153**
Tested on Arch. Resolves the issue #41

### CODE REVIEW

**Comment by nuvious** [comment]
Thanks for the contribution! Will give this a test on my Debian instance this afternoon.

**Comment by DusanLesan** [comment]
Works for me on Arch too

**Review by nuvious — APPROVED** [review]
Tested on Ubuntu today using the README test guide. No issues.

**Comment by nuvious** [comment]
Thanks again @5unr153  and @DusanLesan  for your help and contributions!

**Pull request merged**
